---
# Database configuration
# ======================

mysql_packages: ['mariadb-client', 'mariadb-server']

# mysql_slow_query_log_enabled: yes

# Use this path to activate MySQL log as the mysql
# role does not set it right.
# mysql_log: "/var/log/mysql/mysql.log"
