---

mariadb_version: 10.6

# Additional repositories for MariaDB
apt_sources_repositories:
  mariadb-official:
    dependencies:
      - software-properties-common
      - dirmngr
      - apt-transport-https
    signing_keys:
      - url: https://mariadb.org/mariadb_release_signing_key.asc
    repos:
      - "deb https://ftp.igh.cnrs.fr/pub/mariadb/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
