---

ruby_version: 2.7.0

# Additional repositories for Ruby
apt_sources_repositories:
  # Passenger is used to execute Ruby web applications
  passenger-official:
    dependencies:
      - dirmngr
      - gnupg
      - apt-transport-https
      - ca-certificates
    signing_keys:
      - keyserver: keyserver.ubuntu.com
        id: "561F9B9CAC40B2F7"
    repos:
      - "deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main"
      
  # NodeJS and Yarn are required for Rails 4+ apps
  nodesource.com:
    signing_keys:
      - url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    repos:
      - "deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main"
  yarnpkg.com:
    signing_keys:
      - url: https://dl.yarnpkg.com/debian/pubkey.gpg
    repos:
      - "deb https://dl.yarnpkg.com/debian/ stable main"
