---

mariadb_version: 10.2

# Additional repositories
apt_sources_repositories:
  mariadb-official:
    dependencies:
      - software-properties-common
      - dirmngr
    signing_keys:
      - keyserver: hkp://keyserver.ubuntu.com:80
        id: "0xcbcb082a1bb943db"
      - keyserver: hkp://keyserver.ubuntu.com:80
        id: "0xF1656F24C74CD1D8"
    repos:
      - "deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
