---

mariadb_version: 10.4

# Additional repositories for MariaDB
apt_sources_repositories:
  mariadb-official:
    dependencies:
      - software-properties-common
      - dirmngr
    signing_keys:
      - url: https://downloads.mariadb.com/MariaDB/mariadb-keyring-2019.gpg
    repos:
      - "deb http://downloads.mariadb.com/MariaDB/mariadb-{{ mariadb_version }}/repo/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
