---
# Roles configuration
# ===================

## User accounts

# Administrable
security_sudoers_passwordless: [ administrator ]

# Monit services
monit_services:
  system:     { name: system,         template: monit/system.j2         }
  diskspace:  { name: disk-space,     template: monit/disk-space.j2     }
  cron:       { name: cron,           template: monit/cron.j2           }
  nginx:      { name: nginx,          template: monit/nginx.j2          }
  mysql:      { name: mysql,          template: monit/mysql.j2          }
  openssh:    { name: openssh-server, template: monit/openssh-server.j2 }

