---
- name: Ensure Redis is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ redis_packages }}"

- name: Ensure Redis is running and enabled on boot.
  service:
    name: "redis-server"
    state: "started"
    enabled: "yes"
