---
- name: install packages
  ansible.builtin.apt:
    pkg: monit
    state: present

- name: configure alerts
  ansible.builtin.template:
    src: mail.conf.j2
    dest: /etc/monit/conf.d/mail.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart monit

- name: create a template for silent services
  ansible.builtin.template:
    src: silent.j2
    dest: /etc/monit/templates/silent
    owner: root
    group: root
    mode: 0600
  notify:
    - restart monit

- name: configure status server
  ansible.builtin.copy:
    src: web.conf
    dest: /etc/monit/conf.d/web.conf
    owner: root
    group: root
    mode: 0600
  when: monit_enable_status
  notify:
    - restart monit

- name: create a directory for services definition
  ansible.builtin.file:
    state: directory
    path: /etc/monit/services.d/
    owner: root
    group: root
    mode: 0755

- name: autoload services from the dedicated directory
  ansible.builtin.copy:
    src: services.conf
    dest: /etc/monit/conf.d/services.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart monit
