---
- name: Ensure nginx configuration directories exists
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - conf.d
    - partials.d
    - upstreams.d
    - sites.d

- name: Copy nginx main configuration file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
    
- name: Copy additional MIME types definition file
  copy:
    src: additional-mime.types
    dest: /etc/nginx/additional-mime.types
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx    

- name: Synchronize nginx configuration files
  synchronize:
    src: "{{ item }}/"
    dest: "/etc/nginx/{{ item }}/"
    delete: yes
  with_items:
    - conf.d
    - partials.d
  notify:
    - reload nginx
    
- name: Ensure correct permissions on nginx configuration directories
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes
  with_items:
    - conf.d
    - partials.d
    - upstreams.d
    - sites.d

- name: Ensure default vhost directories exist
  file:
    path: /var/www/default
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes

- name: Setup nginx default vhost
  copy:
    src: vhosts/default
    path: /etc/nginx/sites.d/default
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
