---
- name: install packages
  package:
    name: postfix
    state: present

- name: configure postfix
  import_tasks: configure.yml

- name: enable postfix at boot and start it
  service:
    name: postfix
    state: started
    enabled: yes
