---
- name: install packages
  ansible.builtin.apt:
    name: postfix
    state: present

- name: configure postfix
  ansible.builtin.import_tasks: configure.yml

- name: enable postfix at boot and start it
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: yes
