---
- name: Create group "administrators"
  group:
    name: admins
    state: present
  
- name: Create deployment account
  user:
    name: deployer
    comment: "Deployer account"
    password: "{{ deployer_password }}"
    groups: admins
    append: yes
    shell: "/bin/bash"
    state: present

- name: Authorize key for SSH connections
  authorized_key:
    user: deployer
    key: "{{ lookup('file', '{{ deployer_public_key }}') }}"
    state: present
