---
- name: load application configuration file
  include_vars:
    file: "{{ application_config_file }}"
    name: __application_config

- name: extract application configuration
  set_fact:
    application_config: "{{ __application_config.application }}"

- name: configure environment
  include_role:
    name: environment
  with_items: "{{ application_environments }}"
  loop_control:
    loop_var: application_environment
