---
- name: configure PHP-FPM pool
  template:
    src: pool.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ php_fpm_pool.name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm

- name: create pool's log directory
  file:
    state: directory
    path:  "/var/log/php/{{ php_fpm_pool.name }}"
    owner: "{{ php_fpm_pool.user }}"
    group: "{{ php_fpm_pool.group | default('www-data') }}"
    mode: 0755

- name: create pool's error log
  file:
    state: touch
    path:  "/var/log/php/{{ php_fpm_pool.name }}/error.log"
    owner: "{{ php_fpm_pool.user }}"
    group: "{{ php_fpm_pool.group | default('www-data') }}"
    mode: 0644

- name: create pool's slow log
  file:
    state: touch
    path:  "/var/log/php/{{ php_fpm_pool.name }}/slow.log"
    owner: "{{ php_fpm_pool.user }}"
    group: "{{ php_fpm_pool.group | default('www-data') }}"
    mode: 0644

- name: configure log rotation
  template:
    src: logrotate.conf.j2
    dest: "/etc/logrotate.d/php-fpm-pool-{{ php_fpm_pool.name }}"
    owner: root
    group: root
    mode: 0644

- name: create nginx upstreams directory
  file:
    state: directory
    path:  /etc/nginx/upstreams.d
    owner: root
    group: root
    mode: 0755

- name: configure nginx upstream
  template:
    src: upstream.conf.j2
    dest: "/etc/nginx/upstreams.d/php-fpm.{{ php_fpm_pool.name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
