---
- name: "Configure PHP-FPM pool {{ php_fpm_pool.name }}"
  template:
    src: pool.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ php_fpm_pool.name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm

- name: "Ensure pool log directory exists for pool {{ php_fpm_pool.name }}"
  file:
    state: directory
    path:  "/var/log/php/{{ php_fpm_pool.name }}"
    owner: root
    group: root
    mode: 0755

- name: Ensure nginx upstreams directory exists
  file:
    state: directory
    path:  /etc/nginx/upstreams.d
    owner: root
    group: root
    mode: 0755

- name: "Configure nginx upstream for the PHP-FPM {{ php_fpm_pool.name }} pool"
  template:
    src: upstream.conf.j2
    dest: "/etc/nginx/upstreams.d/php-fpm.{{ php_fpm_pool.name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
