---
# Services setup for a ready to use machine
#
# Use ansible-playbook without extra arguments:
#
#     ansible-playbook 02.0--setup-system-and-services.yml
#
# Please refer to included playbooks for details about
# installed services and their configuration. Each of
# them can be run independently.

## Basic setup for every machine
- ansible.builtin.import_playbook: 02.1-setup-system.yml

## Install and configure MariaDB and Redis on databases servers
- ansible.builtin.import_playbook: 02.2-setup-databases.yml

## Install and configure nginx as web server
- ansible.builtin.import_playbook: 02.3-setup-web-servers.yml

## Install and configure language interpreters
# Ruby
- ansible.builtin.import_playbook: 02.4-setup-ruby.yml
# PHP (and PHP-FPM)
- ansible.builtin.import_playbook: 02.5-setup-php.yml
