---
# Setup and configure nginx on web servers
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook 02.3-setup-web-servers.yml
#
- name: setup and configure web servers
  remote_user: "{{ administrator.user }}"
  become: yes
  
  # Configurations will be applied only on web servers
  hosts: servers_web

  # Some vault vars have to be loaded to not let
  # host_vars files loading fail.
  vars_files:
    - vault/administrators.yml
    - vault/backups.yml

  module_defaults:
    ansible.builtin.apt:
      autoclean: yes
      autoremove: yes
      cache_valid_time: 360

  roles:
    # Install and configure nginx web server
    - role: nginx

    # Configure Monit to watch over nginx services
    - role: monit-service
      monit_service:
        name: nginx
        template: nginx.j2

    # Install lets-encrypt's certbot
    - role: lets-encrypt
