---
# Setup and configure PHP on PHP servers
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook 02.3.2-setup-php.yml
#
- name: setup and configure PHP
  remote_user: administrator
  become: yes
  
  # Configurations will be applied only on PHP servers
  hosts: servers_web_php

  # Some vault vars have to be loaded to not let
  # host_cars files loading fail.
  vars_files:
    - vault/administrators.yml
  
  roles:
    # Install PHP and PHP-FPM
    - role: php
    - role: php-fpm-pool
      php_fpm_pool:
        name: www
        user: www-data
        group: www-data
      handle_nginx: false

    # Install Composer globaly
    - role: php-extra

    # Configure Monit to watch over PHP services
    - role: monit-service
      monit_service:
        name: php-fpm
        template: php-fpm.j2
