---
# Setup and configure Ruby on Ruby servers
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook 02.4-setup-ruby.yml
#
- name: setup and configure ruby
  remote_user: "{{ administrator_name }}"
  become: yes
  
  # Configurations will be applied only on Ruby servers
  hosts: servers_web_ruby

  # Some vault vars have to be loaded to not let
  # host_vars files loading fail.
  vars_files:
    - vault/administrators.yml
  
  roles:
    # Install Ruby and Passenger
    - role: ruby
    - role: ruby-passenger

    # Configure Monit to watch over Passenger
    - role: monit-service
      monit_service:
        name: passenger
        template: passenger.j2
