---
# Setup applications deployments environments
#
# By default, this will setup `staging` and `production`
# environments on targets. To setup development servers, use:
#
#     ansible-playbook 03.0--setup-apps.yml \
#       --extra-vars "environments=['development']"
#
- name: setups applications
  remote_user: administrator
  become: yes
  
  # Configurations will be applied on all servers
  hosts: servers

  vars_files:
    # Some vault vars have to be loaded to not let
    # host_cars files loading fail.
    - vault/administrators.yml

    # Will be used by this playbook
    - vault/applications.yml
    - vault/databases.yml

  
  tasks:

    - name: define configured environments
      set_fact:
        application_environments: "{{ environments | default(['production']) }}"

    - name: configure applications
      include_role:
        role: app
      with_fileglob:
        - 'apps/*.yml'
      loop_control:
        loop_var: application_config_file

    #

    # Create application user accounts, used for application deployment and execution.
    # Credentials and authentication keys are defined per server in `host_vars`.
    #- role: deployers
    # Create PHP-FPM pools (if applicable)
    #- role: php-fpm-pools
    # Create directories with proper permissions
    # Create applications databases (and users)
    # Configure nginx
    # Setup log rotation
    # Ensure applications dependencies available as packages are installed.
    # Configure Monit to watch over application services
    # - applications

