---
# Setup thumbor
#
# Use ansible-playbook without extra arguments:
#
#     ansible-playbook 03.2-setup-thumbor.yml
#
- name: setups thumbor
  remote_user: "{{ administrator.user }}"
  become: yes

  # Configurations will be applied only on servers designated to host an ownCloud instance
  hosts: servers_vendors_thumbor

  vars_files:
    # Some vault vars have to be loaded to not let
    # host_vars files loading fail.
    - vault/administrators.yml
    - vault/backups.yml

  module_defaults:
    ansible.builtin.apt:
      autoclean: yes
      autoremove: yes
      cache_valid_time: 360

  pre_tasks:
    - name: load vendors configuration
      include_vars:
        dir: vault/vendors

  roles:
    - role: thumbor

    # Configure Monit to watch over thumbor
    - role: monit-service
      monit_service:
        name: thumbor
        template: thumbor.j2
