---
# Setup applications deployments environments
#
# By default, this will setup `staging` and `production`
# environments on targets. To setup development servers, use:
#
#     ansible-playbook 04.0--setup-apps.yml \
#       --extra-vars "environments=['development']"
#
- name: setups applications
  remote_user: "{{ administrator_name }}"
  become: yes
  
  # Configurations will be applied on all servers
  hosts: servers

  vars_files:
    # Some vault vars have to be loaded to not let
    # host_vars files loading fail.
    - vault/administrators.yml

    # Will be used by this playbook
    - vault/applications.yml
    - vault/databases.yml

  
  tasks:

    - name: define configured environments
      set_fact:
        application_environments: "{{ environments | default(['production']) }}"

    # Create application user account, used for application deployment and execution.
    # Ensure applications dependencies available as packages are installed.
    # Create directories with proper permissions.
    # Configure nginx and PHP-FPM pools (if applicable).
    # Create applications databases (and users).
    # Setup log rotation.
    # Setup crons.
    # Configure Monit to watch over application services.
    - name: configure applications
      include_role:
        role: app
      with_fileglob:
        - 'apps/*.yml'
      loop_control:
        loop_var: application_config_file
