---
# Setup and configure servers
# 
# Applied configurations:
# 
# - Add dotdeb.org repositories to APT sources for fresher packages
# - Install MySQL  
#   Disable external and anonymous connexions and set up MySQL root credentials (defined per server in `host_vars`).
# - Install PHP and PHP-fpm on PHP servers
# - Install RVM, Ruby and Passenger on Ruby servers 
# - Install and configure nginx web server
# - Install and configure Monit monitoring tool
#
- name: Configure webservers
  hosts: webservers
  remote_user: administrator
  become: yes
  roles:
    - dotdeb
    - uptodate

- name: Configure MySQL
  hosts: webservers
  remote_user: administrator
  become: yes
  roles:
    - mysql

- name: Configure PHP
  hosts: phpservers
  remote_user: administrator
  become: yes
  roles:
    - php

- name: Configure Passenger
  hosts: rubyservers
  remote_user: administrator
  become: yes
  roles: 
    - ruby

- name: Configure nginx
  hosts: webservers
  remote_user: administrator
  become: yes
  roles:
    - nginx

- name: Configure Monit
  hosts: webservers
  remote_user: administrator
  become: yes
  roles:
    - monit
