---
# Setup and configure MySQL on databases servers
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook playbook-03-setup-databases.yml
#
- name: Setup and configure MySQL
  remote_user: administrator
  become: yes
  
  # Configurations will be applied only on MariaDB databases servers
  hosts: servers_db_mariadb
  
  roles:
    # Install MariaDB
    # Disable external and anonymous connexions and set up  
    # root credentials (defined per server in `host_vars`).
    - { role: mariadb, mariadb_conf: { logging: {
        error:      { enabled: 1, file: "/var/log/mysql/error.log" },
        slow_query: { enabled: 1, file: "/var/log/mysql/slow.log" },
      }}
    }
    # Configure Monit to watch over MariaDB services
    - { role: monit-service, monit_services: {
        mariadb: { name: mariadb, template: mariadb.j2 }
      }
    }


- name: Setup and configure Redis
  remote_user: administrator
  become: yes

  # Configurations will be applied only on Redis databases servers
  hosts: servers_db_redis

  roles:
    # Install Redis
    - redis
    # Configure Monit to watch over Redis
    - { role: monit-service, monit_services: {
        redis: { name: redis, template: redis.j2 }
      }
    }
