---
# Initial setup for ansible managment
# 
# On first run, use:
#
#     ansible-playbook playbook-01-make-remotes-administrable.yml \
#       --ask-pass \
#       --extra-vars "hosts={{servername}} remote_user={{username}}"
# 
# `{{servername}}` have to be resolvable. Use /etc/hosts aliases if needed.
# Account named `{{username}}` must exist on remote.
#
# On servers where `{{username}}` is not a sudoer, use instead:
#
#     ansible-playbook playbook-01-make-remotes-administrable.yml \
#       --ask-pass \
#       --ask-become-pass \
#       --extra-vars "hosts={{servername}},become_method=su,remote_user={{username}}"
# 
# After this initial setup, configure SSH to use the administrator account and its key.
# 
# On subsequent runs, use ansible-playbook without extra arguments:
# 
#     ansible-playbook playbook-01-make-remotes-administrable.yml
# 
- name: Initial setup for ansible managment
  remote_user: "{{ remote_user | default('administrator') }}"
  become: true
  become_method: "{{ become_method | default('sudo') }}"
  
  # Configurations will be applied on all remotes
  # (unless others hosts are specified on command line)
  hosts: "{{ hosts | default('servers') }}"
  
  roles:
    # Create an `administrators` user group.
    # Ensure sudo is installed and that the `administrators` group is sudoer
    # Create an `administrator` user account (credentials and authentication
    #   keys are defined per server in `host_vars`)
    - administrable

