---
# Setup and configure MySQL on databases servers
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook playbook-03-setup-databases.yml
#
- name: Setup and configure MySQL on database servers
  remote_user: administrator
  become: yes
  
  # Configurations will be applied only on databases servers
  hosts: database_servers
  
  roles:
    # Install MySQL (MariaDB)  
    # Disable external and anonymous connexions and set up  
    # root credentials (defined per server in `host_vars`).
    - {
        role: mysql,
        
        # Fix log paths to match default package configuration
        # mysql_log:                "/var/log/mysql/mysql.log",
        mysql_slow_query_log_file:  "/var/log/mysql/mysql-slow.log",
        mysql_log_error:            "/var/log/mysql/error.log",
        
      }
    # Configure Monit to watch over MySQL services
    - {
        role: monit-service,
        monit_services: {
          mysql: { name: mysql, template: monit/mysql.j2 }
        }
      }

