---
# Setup and configure nginx on web servers
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook playbook-06-setup-web-servers.yml
#
- name: Setup and configure nginx on web servers
  remote_user: administrator
  become: yes
  
  # Configurations will be applied only on web servers
  hosts: web_servers
  
  roles:
    # Install and configure nginx web server
    - nginx
    # Configure Monit to watch over nginx services
    - {
        role: monit-service,
        monit_services: { 
          nginx: { name: nginx, template: monit/nginx.j2 }
        }
      }

