---
# Setup applications environments for deployments
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook playbook-07-setup-apps.yml
#
- name: Setup applications environments for deployments
  remote_user: administrator
  become: yes
  
  # Configurations will be applied on all servers
  hosts: web_servers
  
  roles:
    # Create a `deployer` user account, used for application deployment.  
    # Credentials and authentication keys are defined per server in `host_vars`.
    - deployable
    # Setup vhosts
    # - Configure nginx
    # - Create directories with proper permissions
    # - Setup log rotation
    - vhosts
    # Create applications databases (and users)
    - databases
    # Ensure applications dependencies available as packages are installed.
    - extra-packages
    # Configure Monit to watch over application services
