---
# Prepare applications deploiment
# 
# Applied configurations:
# 
# - A `deployer` user account, used for application deployment.  
#   Credentials and authentication keys are defined per server in `host_vars`.
# - Setup vhosts
#     - Configure nginx
#     - Create directories with proper permissions
#     - Setup log rotation
#
- name: Create web account
  hosts: webservers
  remote_user: administrator
  become: yes
  roles:
    - deployable
    - vhosts
