---
# Setup applications environments for deployments
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook playbook-07-setup-apps.yml
#
- name: Setups applications
  remote_user: administrator
  become: yes
  
  # Configurations will be applied on all servers
  hosts: web_servers
  
  roles:
    # Create application user accounts, used for application deployment and execution.
    # Credentials and authentication keys are defined per server in `host_vars`.
    - deployers
    # Create PHP-FPM pools (if applicable)
    - php-fpm-pools
    # Create directories with proper permissions
    # Create applications databases (and users)
    # Configure nginx
    # Setup log rotation
    # Ensure applications dependencies available as packages are installed.
    # Configure Monit to watch over application services
    # - applications

