---
- name: Ensure Monit is installed
  apt:
    pkg: monit
    state: installed

- name: Configure Monit alerts
  template:
    src: "mail.conf.j2"
    dest: "/etc/monit/conf.d/mail.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart monit

- name: Add a Monit template for silent services
  template:
    src: "silent.j2"
    dest: "/etc/monit/templates/silent"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart monit

- name: Configure Monit status server
  copy:
    src: "web.conf"
    dest: "/etc/monit/conf.d/web.conf"
    owner: root
    group: root
    mode: 0600
  when: monit_enable_status
  notify:
    - restart monit

- name: Create dedicated directory for services definition
  file:
    state: directory
    path: "/etc/monit/services.d/"
    owner: root
    group: root
    mode: 0755

- name: Configure Monit to load services for the dedicated directory
  copy:
    src: "services.conf"
    dest: "/etc/monit/conf.d/services.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart monit
