---
- name: "Configure Monit for {{ service.value.name }}"
  template:
    src: "{{ service.value.template }}"
    dest: "/etc/monit/conf.d/{{ service.value.name }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload monit
