---
- name: install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: enable service at boot and start it
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes
