---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg
    - build-essential

- name: add GPG key
  shell: curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  args:
    warn: no

- name: download installer
  get_url:
    url: "{{rvm.url}}"
    dest: "{{rvm.temp_installer_path}}"

- name: set the installer as executable
  file:
    path: "{{rvm.temp_installer_path}}"
    mode: 0755

- name: install rvm
  command: "{{rvm.temp_installer_path}} stable"

- name: remove installer
  file:
    path: "{{rvm.temp_installer_path}}"
    state: absent

- name: enable rvm autolibs as root
  command: "/usr/local/rvm/bin/rvm autolibs 3"

- name: add current user to the rvm group
  shell: usermod -a -G rvm `whoami`
  
- name: configure rvmsudo_secure_path
  shell: if sudo grep -q secure_path /etc/sudoers; then sudo sh -c "echo export rvmsudo_secure_path=1 >> /etc/profile.d/rvm_secure_path.sh"; fi

