---
- name: list installed ruby versions
  ansible.builtin.shell: "{{ rvm.path }} list strings executable=/bin/bash"
  register: rubies

- name: check ruby default version
  ansible.builtin.shell: "{{ rvm.path }} list default string executable=/bin/bash"
  register: default_ruby

- name: install required ruby version
  ansible.builtin.shell: "{{ rvm.path }} install {{rvm_default_ruby_version}} executable=/bin/bash"
  when: rubies.stdout.find(rvm_default_ruby_version) == -1

- name: set default ruby version
  ansible.builtin.shell: "{{ rvm.path }} alias create default {{rvm_default_ruby_version}}"
  when: default_ruby.stdout.find(rvm_default_ruby_version) == -1

- name: check bundler installation
  ansible.builtin.shell: "{{ rvm.path }} {{rvm_default_ruby_version}} do gem list executable=/bin/bash"
  register: gem_list

- name: install bundler
  ansible.builtin.shell: "{{ rvm.path }} {{rvm_default_ruby_version}} do gem install bundler executable=/bin/bash"
  when: gem_list.stdout.find('^bundler ') == -1
