---
- name: install Phusion Passenger
  apt:
    name: libnginx-mod-http-passenger
    state: installed

- name: create Phusion Passenger log directory
  file:
    state: directory
    path: /var/log/passenger/
    owner: www-data
    group: adm
    mode: 0750

- name: configure Phusion Passenger log rotation
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/passenger
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- shell: "passenger-config --root"
  register: passenger_root_path

- shell: "passenger-config about ruby-command | egrep 'Command:' | cut -d':' -f2"
  register: passenger_ruby_path

- name: Ensure Passenger module for nginx is enabled
  file:
    src: /usr/share/nginx/modules-available/mod-http-passenger.load
    dest: /etc/nginx/modules-enabled/50-mod-http-passenger.conf
    state: link
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Ensure nginx configuration directory exists
  file:
    path: /etc/nginx/conf.d/additionals/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure Phusion Passenger for nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/additionals/passenger.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
