---
- set_fact:
    directories:
      root:
        path: "/home/deployer/www/{{ vhost.name }}/{{ vhost.environment }}/current/"
        owner: deployer
        group: www-data
        mode: "u=rwx,g=rwx,o=rx"
      logs:
        path: "/home/deployer/logs/{{ vhost.name }}/{{ vhost.environment }}/"
        owner: deployer
        group: www-data
        mode: "u=rwx,g=rwx,o=rx"
      conf: 
        path: "/home/deployer/vhosts-config/{{ vhost.name }}/{{ vhost.environment }}/"
        owner: deployer
        group: www-data
        mode: "u=rwx,g=rwx,o=rx"

- name: Create vhost config file
  template:
    src: "nginx/{{ vhost.type }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ vhost.name }}.{{ vhost.environment }}"
    owner: root
    group: root
    mode: 0644

- name: Create directories
  file:
    state: directory
    path:  "{{ dir.value.path }}"
    owner: "{{ dir.value.owner }}"
    group: "{{ dir.value.group }}"
    mode:  "{{ dir.value.mode }}"
  with_dict: "{{ directories }}"
  loop_control:
    loop_var: dir

- name: Enable vhost
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ vhost.name }}.{{ vhost.environment }}"
    dest: "/etc/nginx/sites-enabled/{{ vhost.name}}.{{ vhost.environment }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Setup log rotation
  template:
    src: logrotate.conf.j2
    dest: "/etc/logrotate.d/{{ vhost.name }}.{{ vhost.environment }}"
    owner: root
    group: root
    mode: 0644

- name: Monitor log rotation
  template:
    src: monit.conf.j2
    dest: "/etc/monit/conf.d/{{ vhost.name }}.{{ vhost.environment }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload monit
