---
- name: install packages
  apt:
    name:
      - apt-config-auto-update
      - unattended-upgrades
    state: present

- name: ensure unattended-upgrades are enabled
  lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: 'APT::Periodic::Enable '
      line: 'APT::Periodic::Enable "1";'
    - regexp: 'APT::Periodic::Update-Package-Lists '
      line: 'APT::Periodic::Update-Package-Lists "1";'
    - regexp: 'APT::Periodic::Download-Upgradeable-Packages '
      line: 'APT::Periodic::Download-Upgradeable-Packages "1";'
    - regexp: 'APT::Periodic::AutocleanInterval '
      line: 'APT::Periodic::AutocleanInterval "7";'
    - regexp: 'APT::Periodic::Unattended-Upgrade '
      line: 'APT::Periodic::Unattended-Upgrade "1";'

- name: configure unattended-upgrades
  lineinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^(//)?Unattended-Upgrade::Automatic-Reboot '
      line: "Unattended-Upgrade::Automatic-Reboot \"false\";"
    - regexp: '^(//)?Unattended-Upgrade::MailOnlyOnError '
      line: "Unattended-Upgrade::MailOnlyOnError \"true\";"
    - regexp: '^(//)?Unattended-Upgrade::Mail '
      line: "Unattended-Upgrade::Mail \"{{ notifications_recipients | join(',') }}\";"
