---

- name: create group 'administrators'
  group:
    name: administrators
    state: present

- name: create group 'applications'
  group:
    name: applications
    state: present

- name: create administrator account
  user:
    name: "{{ administrator.user }}"
    comment: Administrator account
    password: "{{ administrator.pass | password_hash('sha512') }}"
    group: administrators
    groups:
      - applications
    append: yes
    shell: /bin/bash
    state: present
    update_password: "{{ ('always' if administrable_update_administrator_password else 'on_create') }}"

- name: authorize administrator key for SSH connections
  authorized_key:
    user: administrator
    key: "{{ lookup('file', administrator.key) }}"
    state: present

- name: install sudo
  apt:
    name: sudo
    state: present

- name: allow members of 'administrators' to use sudo
  copy:
    src: administrators
    dest: /etc/sudoers.d/administrators
    owner: root
    group: root
    mode: 0440

- name: install acl (used by Ansible)
  apt:
    name: acl
    state: present

- name: configure shell
  copy:
    src: "shell-config/{{ item }}.sh"
    dest: "/etc/profile.d/{{ item }}.sh"
    owner: root
    group: root
    mode: 0644
  with_items:
    - defaults
    - aliases
    - prompt
