---
- name: restart php-fpm
  service:
    name: "php{{ php_version }}-fpm"
    state: "restarted"

- name: restart nginx
  service:
    name: "nginx"
    state: "restarted"
  notify: restart php-fpm
  when: handle_nginx is defined and handle_nginx
