---
- name: install packages
  apt:
    pkg: lftp
    state: present

- name: install backup scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - backup-databases
    - backup-sync

- name: ensure backup user exists
  user:
    name: "{{ mariadb_backup.database.user }}"
    group: "{{ mariadb_backup.database.user }}"
    home: "/var/backups"
    create_home: yes
    shell: /usr/sbin/nologin
    system: yes
    state: present

- name: ensure backup directory exists
  file:
    state: directory
    path: /var/backups/mysql/
    owner: "{{ mariadb_backup.database.user }}"
    group: "{{ mariadb_backup.database.user }}"
    mode: "u=rwX,g=rX,o=rX"

- name: create database backup user
  mysql_user:
    name: "{{ mariadb_backup.database.user }}"
    password: "{{ mariadb_backup.database.pass }}"
    priv: "*.*:USAGE"
    host: localhost
    append_privs: no
    state: present
  no_log: True

- name: grant privileges on database user
  mysql_user:
    name: "{{ mariadb_backup.database.user }}"
    priv: "*.*:{{ item }}"
    host: localhost
    append_privs: yes
    state: present
  no_log: True
  with_items: ['SELECT', 'SHOW VIEW', 'TRIGGER', 'EVENT', 'LOCK TABLES', 'RELOAD']

- name: configure backup credentials
  template:
    src: "my.cnf.j2"
    dest: "/var/backups/.my.cnf"
    owner: "{{ mariadb_backup.database.user }}"
    group: "{{ mariadb_backup.database.user }}"
    mode: 0600

- name: configure databases backup crons
  cron:
    name: "{{ item.time }} backup of all databases"
    user: "{{ mariadb_backup.database.user }}"
    job: "backup-databases {{ item.time }} {{ item.keep }}"
    special_time: "{{ item.time }}"
  with_items:
    - time: daily
      keep: 7
    - time: weekly
      keep: 5
    - time: monthly
      keep: 3

- name: configure backup remote credentials
  template:
    src: "env.j2"
    dest: "/var/backups/.env"
    owner: "{{ mariadb_backup.database.user }}"
    group: "{{ mariadb_backup.database.user }}"
    mode: 0600

- name: configure backup syncing cron
  cron:
    name: "daily backups syncing"
    user: "{{ mariadb_backup.database.user }}"
    job: "backup-sync"
    special_time: daily

- name: ensure log directory exists
  file:
    state: directory
    path: /var/backups/log/
    owner: "{{ mariadb_backup.database.user }}"
    group: "{{ mariadb_backup.database.user }}"
    mode: "u=rwX,g=rX,o=rX"

- name: configure log rotation
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.d/mariadb-backups"
    owner: root
    group: root
    mode: 0644
