---
- name: install packages
  ansible.builtin.apt:
    name: "{{ redis_packages }}"
    state: present

- name: enable service at boot and start it
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: yes
