---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ redis_packages }}"

- name: enable service at boot and start it
  service:
    name: redis-server
    state: started
    enabled: yes
