---
- name: install packages
  apt:
    name: "{{ redis_packages }}"
    state: present

- name: enable service at boot and start it
  service:
    name: redis-server
    state: started
    enabled: yes
