---
- name: install packages
  apt:
    name: "{{ item }}"
    state: "installed"
  with_items: "{{ mariadb_packages | union(['python-mysqldb']) }}"
  register: mariadb_install_packages_task

- name: check packages installation
  set_fact:
    mariadb_packages_installed: "{{ (mariadb_install_packages_task is defined and mariadb_install_packages_task.changed) }}"

- block:
    # Because Ubuntu starts MySQL as part of the install process, we need to stop
    # mysql and remove the logfiles in case the user set a custom log file size.
    - name: stop after initial install
      service:
        name: mysql
        state: stopped

    - name: delete innodb log files created by apt package
      file:
        path: "/var/lib/mysql/{{item}}"
        state: absent
      with_items: [ "ib_logfile0", "ib_logfile1" ]

  when: mariadb_packages_installed
