---
- name: check Composer installation
  stat:
    path: "{{ composer.path }}"
  ignore_errors: True
  register: composer_install_result

- import_tasks: ./install-composer.yml
  when: composer_install_result.stat.exists != true

- name: update Composer
  shell: "{{ composer.path }} self-update --no-progress --stable"
  when: composer_auto_update and composer_install_result.stat.exists != true
