---
- block:
  - name: create database
    community.mysql.mysql_db:
      name: "{{ database.name }}"
      collation: "{{ database.collation | default('utf8_general_ci') }}"
      encoding: "{{ database.encoding | default('utf8') }}"
      state: present

  - name: create database user
    community.mysql.mysql_user:
      name: "{{ database.username }}"
      password: "{{ database.password }}"
      priv: "{{ database.name }}.*:ALL"
      host: localhost
      append_privs: no
      state: present
    no_log: True
  when: inventory_hostname in database.servers
