#!/bin/bash

source $HOME/.env

lftp  -u $BACKUP_SYNC__USER,$BACKUP_SYNC__PASS \
      -p $BACKUP_SYNC__PORT \
      -e "set xfer:log 1;set xfer:log-file $HOME/log/lftp.log; mirror -Rec $HOME/mysql/ /$HOSTNAME/mysql/; exit" \
      $BACKUP_SYNC__HOST > /dev/null
