---
- name: "Configure PHP-FPM pool {{ pool.name }}"
  template:
    src: roles/php-fpm-pools/templates/pool.conf.j2
    dest: /etc/php/7.0/fpm/pool.d/{{ pool.name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  
- name: "Ensure pool log directory exists for pool {{ pool.name }}"
  file:
    state: directory
    path:  "/var/log/php7.0-fpm/{{ pool.name }}"
    owner: root
    group: root
    mode: 0644
  
- name: "Ensure nginx upstreams directory exists"
  file:
    state: directory
    path:  "/etc/nginx/upstreams"
    owner: root
    group: root
    mode: 0755

- name: "Configure nginx upstream for the PHP-FPM {{ pool.name }} pool"
  template:
    src: roles/php-fpm-pools/templates/upstream.conf.j2
    dest: /etc/nginx/upstreams/php7.0-fpm.{{ pool.name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
