---
- name: install packages
  apt:
    name: libnginx-mod-http-passenger
    state: present

- name: check nginx installation
  stat:
    path: /usr/sbin/nginx
  ignore_errors: True
  register: nginx_install_result

- name: set fact about nginx
  set_fact:
    nginx_installed: "{{ nginx_install_result.stat.exists == true }}"

- name: create log directory
  file:
    state: directory
    path: /var/log/passenger/
    owner: www-data
    group: adm
    mode: 0750

- name: configure log rotation
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/passenger
    owner: root
    group: root
    mode: 0644
  notify: restart nginx if exists

- name: get passenger_root
  shell: "passenger-config --root"
  register: passenger_root_path

- name: get passenger_ruby
  shell: "passenger-config about ruby-command | egrep 'Command:' | cut -d':' -f2"
  register: passenger_ruby_path

- name: get rvm_ruby
  shell: "/usr/local/rvm/bin/rvm info {{ ruby_version }} | grep -A4 binaries: | grep ruby: | cut -d'\"' -f2"
  register: rvm_ruby_path

- name: enable Passenger module for nginx
  file:
    src: /usr/share/nginx/modules-available/mod-http-passenger.load
    dest: /etc/nginx/modules-enabled/50-mod-http-passenger.conf
    state: link
    owner: root
    group: root
    mode: 0644
  notify: restart nginx if exists

- name: create nginx additional configurations directory
  file:
    path: /etc/nginx/conf.d/additionals/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure Passenger for nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/additionals/passenger.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx if exists
