---
- name: install packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-common"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-sqlite3"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-zip"
    - "php{{ php_version }}-soap"
    - php-redis
