---
- name: remove default log file
  file:
    path: "/var/log/php{{ php_version }}-fpm.log"
    state: absent

- name: create log directory
  file:
    state: directory
    path: /var/log/php/
    owner: root
    group: adm
    mode: 0755

- name: configure log rotation
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/php
    owner: root
    group: root
    mode: 0644

- name: configure PHP for php-fpm
  template:
    src: php-fpm.ini.j2
    dest: "/etc/php/{{ php_version }}/fpm/conf.d/90-php-fpm.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  
- name: configure PHP for php-cli
  template:
    src: php-cli.ini.j2
    dest: "/etc/php/{{ php_version }}/cli/conf.d/90-php-cli.ini"
    owner: root
    group: root
    mode: 0644
