---
- name: configure PHP-FPM
  ansible.builtin.lineinfile:
    dest: "/etc/php/{{ php_version }}/fpm/php-fpm.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^error_log.?=.+$"
      line: "error_log = /var/log/php/php-fpm.log"
  notify: restart php-fpm

- name: enable service at boot and start it
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: yes
