---
- name: remove default PHP-FPM log file
  file:
    path: "/var/log/php{{ php_version }}-fpm.log"
    state: absent

- name: create PHP-FPM log directory
  file:
    state: directory
    path: /var/log/php/
    owner: root
    group: root
    mode: 0750

- name: configure PHP-FPM log rotation
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/php
    owner: root
    group: root
    mode: 0644

- name: setup PHP-FPM specific INI configuration
  template:
    src: php-fpm.ini.j2
    dest: "/etc/php/{{ php_version }}/fpm/conf.d/90-php-fpm.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  
- name: setup PHP CLI specific INI configuration
  template:
    src: php-cli.ini.j2
    dest: "/etc/php/{{ php_version }}/cli/conf.d/90-php-cli.ini"
    owner: root
    group: root
    mode: 0644
