---
- name: install packages
  ansible.builtin.apt:
    name: "{{ repository.value.dependencies }}"
    state: present
  when: ('dependencies' in repository.value)

- block:
    - name: add GPG key, if defined by (url)
      ansible.builtin.apt_key:
        state: present
        url: "{{ item.url }}"
      with_items: "{{ repository.value.signing_keys | json_query('[*].{ url: url }') }}"
      when: (item.url)

    - name: add GPG key, if defined by (keyserver, id)
      ansible.builtin.apt_key:
        state: present
        keyserver: "{{ item.keyserver }}"
        id: "{{ item.id }}"
      with_items: "{{ repository.value.signing_keys | json_query('[*].{ keyserver: keyserver, id: id }') }}"
      when: (item.keyserver and item.id)

  when: ('signing_keys' in repository.value)

- name: add repository to apt sources
  ansible.builtin.apt_repository:
    filename: "{{ repository.key }}"
    repo: "{{ item }}"
    state: present
    mode: 0644
    update_cache: yes
  with_items: "{{ repository.value.repos }}"
  when: ('repos' in repository.value)

- name: set apt preferences for the added repository
  ansible.builtin.copy:
    content: "{{ repository.value.preferences }}"
    dest: "/etc/apt/preferences.d/{{ repository.key }}"
    owner: root
    group: root
    mode: 0644
  when: ('preferences' in repository.value)
