---
- name: compile domains
  set_fact:
    all_domains: "{{ mains | union(additionals) | union(assets) }}"
  vars:
    mains: "{{ [ vhost.domains.main ] }}"
    additionals: "{{ vhost.domains.additionals | default([]) }}"
    assets: "{{ vhost.domains.assets | default([]) }}"

- name: compile common path and name fragment
  set_fact:
    home_path: "/home/{{ user }}/"
    fragments:
      name: "{{ app_name }}_{{ env_name }}"
      path: "{{ app_name }}/{{ env_name }}"

- name: compile common paths
  set_fact:
    log_path: "{{ home_path }}log/{{ fragments.path }}/"
    web_path: "{{ home_path }}www/{{ fragments.path }}/"

- name: compile nginx paths
  set_fact:
    nginx:
      vhost: "/etc/nginx/sites-available/{{ fragments.name }}"
      certificate: "/etc/nginx/certificates.d/{{ fragments.name }}"

- name: compile vhost paths
  set_fact:
    vhost_paths:
      root: "{{ web_path }}current/"

- name: compile log paths
  set_fact:
    log_paths:
      vhost: "{{ log_path }}vhost/"
      app:   "{{ web_path }}shared/log/"
