---
- name: configure PHP pool
  ansible.builtin.include_role:
    name: php-fpm-pool
  vars:
    php_fpm_pool: "{{ vhost.upstream | combine({ 'user': vhost.owner.name, 'group': 'applications' }) }}"
  when: vhost.type.startswith("php")
