---
- name: create vhost
  template:
    src: "vhosts/{{ vhost.type }}.conf.j2"
    dest: "{{ nginx.vhost }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: enable vhost
  file:
    state: link
    src: "{{ nginx.vhost }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx.vhost | basename }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
