---
- name: create vhost
  template:
    src: "vhosts/{{ vhost.type }}.conf.j2"
    dest: "{{ nginx.vhost }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: extract vhost root path
  slurp:
    src: "{{ nginx.vhost }}"
  register: base64_vhost

- name: extract vhost root path
  set_fact:
    extracted_root_path: "{{ vhost_content | regex_search(root_pattern) | regex_replace(root_pattern, '\\1') }}"
  vars:
    vhost_content: "{{ base64_vhost['content'] | b64decode }}"
    root_pattern: "root ([^;]+);"

- name: combine vhost root path
  set_fact:
    nginx: "{{ nginx | combine({ 'root': extracted_root_path }) }}"

- name: create vhost root directory
  file:
    state: directory
    path:  "{{ nginx.root }}"
    owner: "{{ vhost.owner.name }}"
    group: applications
    mode: "u=rwX,g=rwX,o=X"

- name: create vhost certificate directory
  file:
    state: directory
    path:  "{{ nginx.vhost }}"
    owner: root
    group: root
    mode: 0755

- name: enable vhost
  file:
    state: link
    src: "{{ nginx.vhost }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx.vhost | basename }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
