---
- name: compile certificate path
  ansible.builtin.set_fact:
    cert_path: "/etc/letsencrypt/live/{{ vhost.domains.main }}/"

- name: check certificate
  ansible.builtin.stat:
    path: "{{ cert_path }}"
  register: cert_file

- name: compile SSL options
  ansible.builtin.set_fact:
    certificate_needed: "{{ vhost.ssl and not cert_file.stat.exists }}"

- name: create certificate
  ansible.builtin.include_role:
    role: certificate
  vars:
    owner: "{{ vhost.owner }}"
    domains: "{{ vhost.domains }}"
    root: "{{ nginx.root }}"
  when: certificate_needed

- name: create certificates folder
  ansible.builtin.file:
    state: directory
    path:  "{{ nginx.certificate | dirname }}"
    owner: root
    group: root
    mode:  0755

- name: create SSL config file
  ansible.builtin.template:
    src: certificate.j2
    dest: "{{ nginx.certificate }}.ssl.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
