---
- name: compile SSL options
  set_fact:
    cert_path: "/etc/letsencrypt/live/{{ vhost.domains.main }}/"

- name: check certificate
  stat:
    path: "{{ cert_path }}"
  register: cert_file

- name: compile SSL options
  set_fact:
    certificate_needed: "{{ ssl and not cert_file.stat.exists }}"

- name: create certificate
  include_role:
    role: certificate
  vars:
    email: "{{ email }}"
    main_domain: "{{ vhost.domains.main }}"
    all_domain: "{{ all_domains }}"
    root_path: "{{ vhost_root_path }}"
  when: certificate_needed

- name: create certificates folder
  file:
    state: directory
    path:  "{{ nginx.certificate | dirname }}"
    owner: root
    group: root
    mode:  0755

- name: create SSL config file
  template:
    src: certificate.j2
    dest: "{{ nginx.certificate }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
