---
- name: Setup log rotation
  template:
    src: logrotate.conf.j2
    dest: "/etc/logrotate.d/{{ fragments.name }}"
    owner: root
    group: root
    mode: 0644

- name: Monitor log rotation
  template:
    src: monit.conf.j2
    dest: "/etc/monit/conf.d/{{ fragments.name }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload monit
