---

- include_tasks: compile-vars.yml

- name: create directories
  file:
    state: directory
    path:  "{{ dir.value.path }}"
    owner: "{{ dir.value.owner }}"
    group: "{{ dir.value.group }}"
    mode:  "{{ dir.value.mode }}"
  with_dict: "{{ directories }}"
  loop_control:
    loop_var: dir

- include_tasks: vhost.yml

- include_role:
    name: php-fpm-pool
    private: True
  vars:
    php_fpm_pool: "{{ vhost.upstream | combine({ 'user': user, 'group': 'applications' }) }}"
  when: '"upstream" in vhost'

- include_tasks: ssl.yml
  when: ssl

- include_tasks: logs.yml
