---

- name: compile variables
  include_tasks: 01-compile-vars.yml

- name: create Capistrano directories
  include_tasks: 02-capistrano-directories.yml

- name: configure PHP pool
  include_role:
    name: php-fpm-pool
    private: True
  vars:
    php_fpm_pool: "{{ vhost.upstream | combine({ 'user': user, 'group': 'applications' }) }}"
  when: '"upstream" in vhost'

- name: configure logs
  include_tasks: 03-logs.yml

# Configure vhost without HTTPS support
- name: configure vhost
  include_tasks: 04-vhost.yml
  vars:
    ssl: false

- block:
    # Ensure nginx is reloaded and support the newly created vhost
    - meta: flush_handlers

    - name: configure SSL certificate
      include_tasks: 05-ssl.yml

    # Reconfigure vhost with full HTTPS support
    - name: configure vhost
      include_tasks: 04-vhost.yml
  when: ssl
