---
- name: Ensure nginx sites directory exists
  file:
    state: directory
    path:  "{{ nginx.vhost | dirname }}"
    owner: root
    group: root
    mode: 0755

- name: Create nginx config file
  template:
    src: "vhosts/{{ vhost.type }}.conf.j2"
    dest: "{{ nginx.vhost }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
