---
- name: check if chapecron is installed
  stat:
    path: "{{chapecron.path}}"
  register: chapecron_path

- block:
  - name: download archive
    get_url:
      url: "{{chapecron.archive_url}}"
      dest: "{{chapecron.archive_path}}"

  - name: extract archive
    ansible.builtin.unarchive:
      remote_src: yes
      src: "{{chapecron.archive_path}}"
      dest: "{{chapecron.extract_path}}"

  - name: build chapecron
    community.general.make:
      chdir: "{{chapecron.installer_path}}"

  - name: install chapecron
    become: yes
    community.general.make:
      chdir: "{{chapecron.installer_path}}"
      target: install

  - name: remove installer
    file:
      path: "{{chapecron.installer_path}}"
      state: absent

  - name: remove archive
    file:
      path: "{{chapecron.archive_path}}"
      state: absent
  when: "chapecron_path.stat.exists == False"
