---
- name: compile cron params
  ansible.builtin.set_fact:
    cron_params:
      user: "{{ owner.name }}"
      state: present
      env:
        MAILTO: "{{ owner.email }}"

- name: setup cron job
  ansible.builtin.cron: "{{ cron | combine(cron_params) }}"
