---
- name: create or renew certificate
  shell: |
    certbot certonly --webroot \
      -n --agree-tos -m gael-ian@notus.sh \
      --cert-name {{ main_domain }} \
      --webroot-path {{ root_path }} \
      --domains {{ all_domains | join(',') }}
