---
- name: create or renew certificate
  shell: |
    certbot certonly --webroot \
      -n --agree-tos -m gael-ian@notus.sh \
      --cert-name {{ vhost.domains.main }} \
      --webroot-path {{ directories.root.path }} \
      --domains {{ all_domains | join(',') }}
