---
- name: compile certificate options
  ansible.builtin.set_fact:
    all_domains: "{{ mains | union(additionals) | union(assets) }}"
  vars:
    mains: "{{ [ domains.main ] }}"
    additionals: "{{ domains.additionals | default([]) }}"
    assets: "{{ domains.assets | default([]) }}"

- name: create or renew certificate
  ansible.builtin.shell: |
    certbot certonly --webroot \
      -n --agree-tos -m {{ owner.email }} \
      --cert-name {{ domains.main }} \
      --webroot-path {{ root }} \
      --domains {{ all_domains | join(',') }}
