---
- name: create Capistrano directories
  ansible.builtin.file:
    state: directory
    path:  "{{ capistrano_root }}{{ item }}"
    owner: "{{ user }}"
    group: applications
    mode: "u=rwX,g=rwX,o=X"
  with_items: [ "shared", "releases" ]

- name: list releases
  ansible.builtin.find:
    path: "{{ capistrano_root }}releases"
    file_type: directory
  register: releases

- block:
    - name: create initial release directory
      ansible.builtin.file:
        state: directory
        path:  "{{ capistrano_root }}releases/0"
        owner: "{{ user }}"
        group: applications
        mode: "u=rwX,g=rwX,o=X"

    - name: link initial release to current release
      ansible.builtin.file:
        state: link
        src: "{{ capistrano_root }}releases/0"
        dest:  "{{ capistrano_root }}current"
  when: releases.matched | int == 0
