---
- name: install packages
  apt:
    name:
      - nginx
      - nginx-extras
    state: present

- name: enable service at boot and start it
  service:
    name: nginx
    state: started
    enabled: yes
