---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - nginx-extras

- name: enable service at boot and start it
  service:
    name: nginx
    state: started
    enabled: yes
