---
- name: Ensure nginx configuration directories exists
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - conf.d
    - conf.d/additionals
    - partials.d
    - upstreams.d
    - sites-available
    - sites-enabled

- name: Copy nginx main configuration file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
    
- name: Copy additional configuration files
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - conf.d/cache.conf
    - conf.d/geoip.conf
    - conf.d/gzip.conf
    - conf.d/http.conf
    - conf.d/limits.conf
    - conf.d/logs.conf
    - conf.d/mime.conf
    - additional-mime.types
    - conf.d/security.conf
    - conf.d/ssl.conf
  notify:
    - reload nginx    

- name: Synchronize nginx configuration partials
  synchronize:
    src: partials.d/
    dest: /etc/nginx/partials.d/
    delete: yes
  notify:
    - reload nginx
    
- name: Ensure correct permissions on nginx configuration directories
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  with_items:
    - conf.d
    - partials.d

- name: Ensure default vhost directories exist
  file:
    path: /var/www/default
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes

- name: Setup nginx default vhost
  copy:
    src: default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Enable nginx default vhost
  file:
    state: link
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
