---
- name: create configuration directories
  ansible.builtin.file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - conf.d
    - conf.d/additionals
    - partials.d
    - upstreams.d
    - certificates.d

- name: copy additional configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - additional-mime.types
    - conf.d/mime.conf
    - conf.d/limits.conf
    - conf.d/cache.conf
    - conf.d/http.conf
    - conf.d/security.conf
    - conf.d/logs.conf
    - conf.d/geoip.conf
    - conf.d/gzip.conf
    - conf.d/ssl.conf
  notify:
    - reload nginx    

- name: copy configuration partials
  ansible.posix.synchronize:
    src: partials.d/
    dest: /etc/nginx/partials.d/
    delete: yes
  notify:
    - reload nginx

- name: set permissions on configuration directories
  ansible.builtin.file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  with_items:
    - conf.d
    - partials.d

- name: copy main configuration file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: create default vhost directory
  ansible.builtin.file:
    path: /var/www/default
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes

- name: remove default vhost configuration
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: setup default vhost
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: enable default vhost
  ansible.builtin.file:
    state: link
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
