---

- name: install packages
  apt:
    name: nginx
    state: present

- name: configure nginx
  import_tasks: configure.yml

- name: enable nginx at boot and start it
  service:
    name: nginx
    state: started
    enabled: yes
