---

- name: install packages
  ansible.builtin.apt:
    name:
      - nginx
      - apache2-utils # For htpasswd
    state: present

- name: configure nginx
  ansible.builtin.import_tasks: configure.yml

- name: enable nginx at boot and start it
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
