---

# System administrator
administrator_name: "{{ administrators['server-20'].system.name }}"
administrator_password: "{{ administrators['server-20'].system.name }}"
administrator_public_key: vault/keys/server-20/administrator.rsa.pub

# MariaDB administrator
mariadb_root_password: "{{ administrators['server-20'].mariadb.pass }}"

# MariaDB backups
mariadb_backup:
  user:
    name: "{{ administrators['server-20']['mariadb-backup'].name }}"
    pass: "{{ administrators['server-20']['mariadb-backup'].pass }}"
  remote:
    host: "{{ administrators['server-20']['mariadb-remote'].host }}"
    port: "{{ administrators['server-20']['mariadb-remote'].port }}"
    user: "{{ administrators['server-20']['mariadb-remote'].user }}"
    pass: "{{ administrators['server-20']['mariadb-remote'].pass }}"


# ownCloud configuration
owncloud_config:
  vhost:
    ssl: "{{ vendors['server-20'].owncloud.ssl }}"
    domains: "{{ vendors['server-20'].owncloud.domains }}"
    owner: "{{ vendors['server-20'].owncloud.owner }}"
  database:
    type: "mysql"
    host: "localhost"
    name: "{{ databases['server-20'].owncloud.name }}"
    user: "{{ databases['server-20'].owncloud.user }}"
    pass: "{{ databases['server-20'].owncloud.pass }}"
  admin:
    user: "{{ administrators['server-20'].owncloud.user }}"
    pass: "{{ administrators['server-20'].owncloud.pass }}"
  data_dir: "/var/www/owncloud/data"

# thumbor configuration
thumbor_config:
  vhost:
    ssl: "{{ vendors['server-20'].thumbor.ssl }}"
    domains: "{{ vendors['server-20'].thumbor.domains }}"
    owner: "{{ vendors['server-20'].thumbor.owner }}"
  security_key: "{{ vendors['server-20'].thumbor.security_key }}"
  allowed_sources: "{{ vendors['server-20'].thumbor.allowed_sources }}"
