---

# System administrator
administrator_password: "{{ administrator_passwords['server-20'] }}"
administrator_public_key: vault/keys/server-20/administrator.rsa.pub

# MariaDB administrator
mariadb_root_password: "{{ database_administrator_passwords['server-20'] }}"
