---
- name: "Configure PHP-FPM pool {{ pool.name }}"
  template:
    src: pool.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ pool.name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  
- name: "Ensure pool log directory exists for pool {{ pool.name }}"
  file:
    state: directory
    path:  "/var/log/php/{{ pool.name }}"
    owner: root
    group: root
    mode: 0644
  
- name: "Ensure nginx upstreams directory exists"
  file:
    state: directory
    path:  /etc/nginx/upstreams.d
    owner: root
    group: root
    mode: 0755

- name: "Configure nginx upstream for the PHP-FPM {{ pool.name }} pool"
  template:
    src: upstream.conf.j2
    dest: "/etc/nginx/upstreams.d/php-fpm.{{ pool.name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
