---
- name: Install system requirements
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - apt-transport-https
    - lsb-release
    - ca-certificates

- name: Import packages.sury.org GPG keys
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: "present"

- name: Add packages.sury.org repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
    update_cache: "yes"
