---
- name: create group 'applications'
  group:
    name: applications
    state: present

- name: create user account
  user:
    name: "{{ user.name }}"
    password: "{{ user.password|password_hash('sha512') }}"
    groups:
      - applications
    append: yes
    shell: /bin/bash
    state: present

- name: authorize owner key for SSH connections
  authorized_key:
    user: "{{ user.name }}"
    key: "{{ lookup('file', '{{ user.key }}') }}"
    state: present
