---
- name: setup nginx global configuration
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/{{ item|basename }}
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - global/*.conf
  notify:
    - reload nginx

- name: create nginx configuration partials directory
  file:
    path: /etc/nginx/partials.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy nginx configuration partials
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/partials.d/{{ item|basename }}
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - partials/*.conf
  notify:
    - reload nginx
