---
- name: "Configure Monit for {{ monit_service.name }}"
  template:
    src: "{{ monit_service.template }}"
    dest: "/etc/monit/services.d/{{ monit_service.name }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload monit
