---
# Basic setup for every machine
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook playbooks/02.1-setup-system.yml
#
- name: System setup for every machine
  remote_user: administrator
  become: yes
  
  # Configurations will be applied on all servers
  hosts: servers
  
  roles:
    # Add repositories to APT sources
    - role: apt-sources
    # Apply all pending updates (except in Virtualbox VMs, as updates
    # can break Guest Additions kernel module)
    - role: uptodate
      when: (ansible_bios_version != 'VirtualBox')
    # Ensure some basic packages are installed.  
    # See `roles/base-packages/defaults/main.yml` 
    # for a list of installed packages.
    - role: base-packages
    # Ensure servers are (basically) secured by
    # - Disabling SSH root login and password authentication
    # - Installing fail2ban with default configuration
    # - Enabling automatic security updates
    - role: security
    # Install and globally configure Monit for monitoring
    - role: monit
    # Configure Monit with basic system watches
    - role: monit-service
      monit_services:
        system:
          name: system
          template: system.j2
        diskspace:
          name: disk-space
          template: disk-space.j2
        cron:
          name: cron
          template: cron.j2
        openssh:
          name: openssh-server
          template: openssh-server.j2
