---
# Setup and configure MariaDB and Redis on databases servers
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook playbooks/02.2-setup-databases.yml
#
- name: setup and configure databases
  remote_user: administrator
  become: yes
  
  # Configurations will be applied only on MariaDB databases servers
  hosts: servers_db_mariadb
  
  roles:
    # Install MariaDB
    # Disable external and anonymous connexions and set up  
    # root credentials (defined per server in `host_vars`).
    - role: mariadb
      mariadb_conf:
        logging:
          error:
            enabled: yes
            file: /var/log/mysql/error.log
          slow_query:
            enabled: yes
            file: /var/log/mysql/slow.log

    # Configure Monit to watch over MariaDB services
    - role: monit-service
      monit_service:
        name: mariadb
        template: mariadb.j2


- name: Setup and configure Redis
  remote_user: administrator
  become: yes

  # Configurations will be applied only on Redis databases servers
  hosts: servers_db_redis

  roles:
    # Install Redis
    - role: redis

    # Configure Monit to watch over Redis
    - role: monit-service
      monit_service:
        name: redis
        template: redis.j2
