---
# Setup and configure nginx on web servers
# 
# Use ansible-playbook without extra arguments:
# 
#     ansible-playbook playbooks/02.4-setup-web-servers.yml
#
- name: setup and configure web servers
  remote_user: administrator
  become: yes
  
  # Configurations will be applied only on web servers
  hosts: servers_web
  
  roles:
    # Install and configure nginx web server
    - role: nginx

    # Configure Monit to watch over nginx services
    - role: monit-service
      monit_service:
        name: nginx
        template: nginx.j2

    # Install lets-encrypt's certbot
    - role: lets-encrypt
