---
- name: install Phusion Passenger
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - nginx-extras
    - passenger

- name: create Phusion Passenger log directory
  file:
    state: directory
    path: "/var/log/passenger/"
    owner: www-data
    group: adm
    mode: 0750

- name: configure Phusion Passenger log rotation
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/passenger
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- shell: "passenger-config --root"
  register: passenger_root_path

- shell: "passenger-config about ruby-command | egrep 'Command:' | cut -d':' -f2"
  register: passenger_ruby_path

- name: detect if nginx is already installed
  stat:
    path: "/usr/sbin/nginx"
  register: nginx_stats

- name: configure Phusion Passenger for nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/modules-available/passenger.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
