---
- name: install system requirements
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - curl
    - gnupg
    - build-essential

- name: add RVM gpg key
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: downloading RVM installer
  get_url:
    url: "{{rvm.url}}"
    dest: "{{rvm.temp_installer_path}}"

- name: set executable RVM installer
  file:
    path: "{{rvm.temp_installer_path}}"
    mode: 0755

- name: installing RVM
  command: "{{rvm.temp_installer_path}} stable"

- name: removing RVM installer
  file:
    path: "{{rvm.temp_installer_path}}"
    state: absent

- name: setting RVM autolibs on as root
  command: "/usr/local/rvm/bin/rvm autolibs 3"

- name: add current user to rvm group
  shell: usermod -a -G rvm `whoami`
  
- name: configure rvmsudo_secure_path
  shell: if sudo grep -q secure_path /etc/sudoers; then sudo sh -c "echo export rvmsudo_secure_path=1 >> /etc/profile.d/rvm_secure_path.sh"; fi

